// ThaiAI Core Implementation
// =============================
// Nucleo dell'assistente AI locale ThaiAI.

#include "thai_ai.h"
#include <mm.h>
#include <sched.h>

static thai_ai_state_t g_ai;

void thai_ai_init(void) {
    memset(&g_ai, 0, sizeof(g_ai));
    g_ai.model_count = 0;
    g_ai.automation_count = 0;

    strcpy(g_ai.system_prompt,
        "You are ThaiAI, the integrated AI assistant for ThaiOS. "
        "You can help with system control, file search, automation, "
        "code generation, translation, and summarization.");

    kprintf("[THAI_AI] ThaiAI assistant initialized\n");
    kprintf("[THAI_AI] System prompt loaded (%llu chars)\n", (u64)strlen(g_ai.system_prompt));

    // Auto-create some default automations
    thai_ai_create_automation("greeting", "hello thai", "echo Hello! I am ThaiAI, your assistant.");
    thai_ai_create_automation("time", "what time", "echo System time query (TODO)");
}

int thai_ai_load_model(const char *name, ai_model_type_t type, const char *path) {
    if (g_ai.model_count >= THAI_AI_MAX_MODELS) return -ENOMEM;

    ai_model_t *model = &g_ai.models[g_ai.model_count];
    strncpy(model->name, name, sizeof(model->name) - 1);
    model->type = type;
    strncpy(model->model_path, path, sizeof(model->model_path) - 1);
    model->loaded = false;
    model->context_size = 2048;
    model->memory_usage = 0;
    model->priv = NULL;
    model->infer = NULL;

    kprintf("[THAI_AI] Model '%s' registered (%s)\n", name, path);
    g_ai.model_count++;
    return SUCCESS;
}

int thai_ai_query(const char *input, char *output, usize max_out) {
    kprintf("[THAI_AI] Query: %s\n", input);

    // 1. Check automations first
    for (int i = 0; i < g_ai.automation_count; i++) {
        if (g_ai.automations[i].enabled &&
            strstr(input, g_ai.automations[i].trigger)) {
            kprintf("[THAI_AI] Automation triggered: %s\n", g_ai.automations[i].name);
            g_ai.automations[i].trigger_count++;
            snprintf(output, max_out, "%s", g_ai.automations[i].action);
            return SUCCESS;
        }
    }

    // 2. Classify intent
    ai_intent_t intent = thai_ai_classify_intent(input);
    kprintf("[THAI_AI] Intent classified: %d\n", intent);

    // 3. Route to handler
    switch (intent) {
        case INTENT_OPEN_APP: {
            // Extract app name from input
            char app_name[64] = {0};
            // Simple extraction: words after "open" or "launch"
            const char *open_markers[] = {"open ", "launch ", "run ", "start ", NULL};
            for (int m = 0; open_markers[m]; m++) {
                const char *found = strstr(input, open_markers[m]);
                if (found) {
                    strncpy(app_name, found + strlen(open_markers[m]), sizeof(app_name) - 1);
                    // Trim trailing space/punctuation
                    char *end = app_name + strlen(app_name) - 1;
                    while (end >= app_name && (*end == ' ' || *end == '.' || *end == '!'))
                        *end-- = '\0';
                    break;
                }
            }
            if (app_name[0]) {
                thai_ai_open_app(app_name);
                snprintf(output, max_out, "Opening %s...", app_name);
            } else {
                snprintf(output, max_out, "Which application would you like to open?");
            }
            break;
        }

        case INTENT_SYSTEM_INFO: {
            char info[2048];
            thai_ai_get_system_info(info, sizeof(info));
            snprintf(output, max_out, "%s", info);
            break;
        }

        case INTENT_TRANSLATE: {
            // Extract text and target language
            char text[1024] = {0};
            char lang[32] = "english";
            // TODO: smarter parsing
            snprintf(output, max_out, "Translation feature (stub)");
            break;
        }

        case INTENT_GENERATE_CODE: {
            // Extract code generation request
            const char *code_marker = "code ";
            const char *found = strstr(input, code_marker);
            if (found) {
                snprintf(output, max_out,
                    "// Generated by ThaiAI\n// Prompt: %s\n\nfn main() {\n    println!(\"Hello from ThaiOS\");\n}\n",
                    found + 5);
            }
            break;
        }

        default:
            snprintf(output, max_out,
                "I understand you said: '%s'. "
                "I can help with: opening apps, searching files, "
                "system information, translations, summaries, and code generation. "
                "How can I assist?", input);
            break;
    }

    kprintf("[THAI_AI] Response: %s\n", output);
    return SUCCESS;
}

ai_intent_t thai_ai_classify_intent(const char *input) {
    // Rule-based intent classification
    const char *lower = input;

    if (strstr(lower, "open ") || strstr(lower, "launch ") ||
        strstr(lower, "start ") || strstr(lower, "run ")) {
        return INTENT_OPEN_APP;
    }
    if (strstr(lower, "search") || strstr(lower, "find ")) {
        return INTENT_SEARCH_FILE;
    }
    if (strstr(lower, "system") || strstr(lower, "info") ||
        strstr(lower, "status") || strstr(lower, "memory") ||
        strstr(lower, "cpu")) {
        return INTENT_SYSTEM_INFO;
    }
    if (strstr(lower, "translate") || strstr(lower, "traduci")) {
        return INTENT_TRANSLATE;
    }
    if (strstr(lower, "summarize") || strstr(lower, "summary") ||
        strstr(lower, "riassumi")) {
        return INTENT_SUMMARIZE;
    }
    if (strstr(lower, "code") || strstr(lower, "generate") ||
        strstr(lower, "function") || strstr(lower, "script")) {
        return INTENT_GENERATE_CODE;
    }
    if (strstr(lower, "automation") || strstr(lower, "auto")) {
        return INTENT_CREATE_AUTOMATION;
    }
    if (strstr(lower, "remind") || strstr(lower, "reminder")) {
        return INTENT_SET_REMINDER;
    }
    if (strstr(lower, "brightness") || strstr(lower, "volume") ||
        strstr(lower, "wifi") || strstr(lower, "bluetooth")) {
        return INTENT_CONTROL_HARDWARE;
    }

    return INTENT_UNKNOWN;
}

int thai_ai_open_app(const char *app_name) {
    kprintf("[THAI_AI] Opening application: %s\n", app_name);
    // TODO: search PATH, launch process
    return SUCCESS;
}

int thai_ai_search_files(const char *query, char *results, usize max_size) {
    kprintf("[THAI_AI] Searching files: %s\n", query);
    // TODO: VFS search
    snprintf(results, max_size, "Search results for '%s' (stub)", query);
    return SUCCESS;
}

int thai_ai_get_system_info(char *info, usize max_size) {
    char buf[2048];
    snprintf(buf, sizeof(buf),
        "ThaiOS v%d.%d.%d\n"
        "Architecture: x86_64\n"
        "Kernel: Microkernel Hybrid\n"
        "Memory: %llu MB free\n"
        "Processes: %d running\n"
        "Uptime: TODO\n",
        THAIOS_VERSION_MAJOR, THAIOS_VERSION_MINOR, THAIOS_VERSION_PATCH,
        pmm_free_pages_count() * 4 / 1024,
        0  // TODO: process count
    );
    snprintf(info, max_size, "%s", buf);
    return SUCCESS;
}

int thai_ai_create_automation(const char *name, const char *trigger, const char *action) {
    if (g_ai.automation_count >= THAI_AI_MAX_AUTOMATIONS) return -ENOMEM;

    ai_automation_t *a = &g_ai.automations[g_ai.automation_count];
    strncpy(a->name, name, sizeof(a->name) - 1);
    strncpy(a->trigger, trigger, sizeof(a->trigger) - 1);
    strncpy(a->action, action, sizeof(a->action) - 1);
    a->enabled = true;
    a->trigger_count = 0;
    g_ai.automation_count++;

    kprintf("[THAI_AI] Automation created: '%s' -> '%s'\n", trigger, action);
    return SUCCESS;
}
